server:
  port: 10020
#---------------------------------------------------------------------
spring:
  profiles:
    active: native
  application:
    name: config-server
#---------------------------------------------------------------------
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    status-page-url-path: /actuator/info #eureka注册中心的url link
    health-check-url-path: /actuator/health #健康检查的url
    hostname: localhost
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true #是否注册到注册中心
    fetch-registry: true #是否从注册中心拉取注册服务列表
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10010/eureka/
#---------------------------------------------------------------------
#监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#---------------------------------------------------------------------
info:
  version: 1.0.0
  app:
    name: ${spring.application.name}
  company:
    name: Noageir
  build:
    artifacitd: '@project.artifactId@'
    version: '@project.version@'

#---------------------------------------------------------------------